CONTACT: false
ENTITY_ATTACK: false
ENTITY_SWEEP_ATTACK: false
PROJECTILE: false
SUFFOCATION: false
FALL: true
FIRE: false
FIRE_TICK: false
MELTING: false
LAVA: false
DROWNING: false
BLOCK_EXPLOSION: false
ENTITY_EXPLOSION: false
VOID: false
LIGHTNING: false
SUICIDE: false
STARVATION: false
POISON: false
MAGIC: false
WITHER: false
FALLING_BLOCK: false
THORNS: false
DRAGON_BREATH: false
CUSTOM: false
FLY_INTO_WALL: false
HOT_FLOOR: false
CRAMMING: false
DRYOUT: false